services:
  frontend:
    image: ghcr.io/minxseox/fe_zzaptalk:${IMAGE_TAG:-latest}
    container_name: zzaptalk-frontend
    restart: always
    ports:
      - "3000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
