version: "3.8"

services:
  frontend:
    image: minxseox/my-expo-web:latest # 또는 build: . 쓰고 직접 빌드해도 됨
    container_name: zzaptalk-frontend
    restart: always
    ports:
      - "3000:80" # 브라우저: http://localhost:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
