server {
    listen 80;

    # 1. 정적 파일 (Expo Web 빌드 결과)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. 백엔드 API 프록시
    location /api {
        # 🔥 여기만 환경변수로 주입받을 거야
        proxy_pass ${API_URL};

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
